package entity;

// Generated 9 déc. 2015 14:27:09 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name = "FOURNISSEUR")
public class Fournisseur implements java.io.Serializable {

	private String idF;
	private String nom;
	private String adresse;

	public Fournisseur() {
	}

	public Fournisseur(String idF, String nom, String adresse) {
		this.idF = idF;
		this.nom = nom;
		this.adresse = adresse;
	}

	@Id
	@Column(name = "ID_F", unique = true, nullable = false, length = 4000)
	public String getIdF() {
		return this.idF;
	}

	public void setIdF(String idF) {
		this.idF = idF;
	}

	@Column(name = "NOM", nullable = false, length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "ADRESSE", nullable = false, length = 4000)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

}
