package entity;

// Generated 9 déc. 2015 14:27:09 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "PRODUIT")
public class Produit implements java.io.Serializable {

	@Override
	public String toString() {
		return "Produit [id=" + id + ", nom=" + nom + ", quantite=" + quantite + "]";
	}

	private String id;
	private String nom;
	private BigDecimal quantite;

	public Produit() {
	}

	public Produit(String id, String nom) {
		this.id = id;
		this.nom = nom;
	}

	public Produit(String id, String nom, BigDecimal quantite) {
		this.id = id;
		this.nom = nom;
		this.quantite = quantite;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 4000)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NOM", nullable = false, length = 4000)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "QUANTITE", precision = 22, scale = 0)
	public BigDecimal getQuantite() {
		return this.quantite;
	}

	public void setQuantite(BigDecimal quantite) {
		this.quantite = quantite;
	}

}
